### PR TITLE
[WIP] Website Cleanup

### PR DESCRIPTION
**Pull request by skmedix**
This is still _Work In Progress_ ;)

Give me max. one week.

### CODE REVIEW

**Comment by skmedix** [comment]
@jfoenixadmin 
image

Is this navbar is good for you? It's definitely more responsive and clean.

Before:
image

After:
image

**Comment by skmedix** [comment]
I wanted to still work on this PR, 😄 but visual changes like in screens above should be in a separate PR. So.. It's even better.

**Comment by jfoenixadmin** [comment]
it seems much better 👍 feel free to create PR when you finish.

Regards,

**Comment by skmedix** [comment]
Sure I do 😉

**Pull request merged**
